//! Unified internal representation of conversation items.
//!
//! Provider adapters map between this enum and wire formats (OpenAI Chat
//! Completions, OpenAI Responses, Anthropic Messages). Rollout stores
//! these as structured events. The context projection trims or elides
//! large items without touching the source data.

use crate::id::ToolCallId;
use serde::{Deserialize, Serialize};

/// Every item that can appear in the model's working context.
///
/// This is the *internal* representation — never a raw provider type.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ContextItem {
    /// High-authority instructions (model base instructions, managed policy).
    System { content: String },
    /// Developer-level instructions (AGENTS.md, project rules).
    Developer { content: String },
    /// User message or synthetic user-like injection.
    User {
        content: String,
        /// Optional stable identifier for deduplication across turns.
        message_id: Option<String>,
    },
    /// Model-generated text response.
    Assistant { content: String },
    /// A tool invocation generated by the model.
    ToolCall {
        call_id: ToolCallId,
        name: String,
        arguments: serde_json::Value,
    },
    /// Result returned by a tool execution.
    ToolResult {
        call_id: ToolCallId,
        content: String,
        is_error: bool,
    },
    /// Replacement for a window of compressed context items.
    CompactionSummary {
        summary: String,
        /// Monotonically increasing compaction window number.
        window_number: u64,
    },
    /// Summary of model reasoning from a previous step.
    ReasoningSummary { content: String },
    /// Reference to a binary asset stored in the blob store.
    ImagePlaceholder { mime_type: String, artifact_ref: String },
}

impl ContextItem {
    /// Approximate token weight for prioritization and trimming.
    /// Uses a simple heuristic: ~3.5 chars per token for English text.
    pub fn estimated_tokens(&self) -> usize {
        let text: &str = match self {
            Self::System { content } => content,
            Self::Developer { content } => content,
            Self::User { content, .. } => content,
            Self::Assistant { content } => content,
            Self::CompactionSummary { summary, .. } => summary,
            Self::ReasoningSummary { content } => content,
            Self::ToolCall { arguments, .. } => return arguments.to_string().len() / 3,
            Self::ToolResult { content, .. } => content,
            Self::ImagePlaceholder { .. } => return 20,
        };
        text.len().max(4) / 3
    }

    /// Convert a ToolResult into a synthetic User message for round-trip
    /// injection. This is used when tool responses need to be re-injected
    /// into the context as user-visible content (e.g. after compaction
    /// or when the provider doesn't support native tool result messages).
    pub fn tool_result_as_user(call_id: &ToolCallId, tool_name: &str, content: &str) -> Self {
        ContextItem::User {
            content: format!(
                "[Tool Result: {} (call_id: {})]\n{}",
                tool_name, call_id, content
            ),
            message_id: Some(format!("tool_resp_{}", call_id)),
        }
    }

    /// Build a synthetic system notification (e.g. for session events,
    /// compaction notifications, or runtime warnings).
    pub fn synthetic_notification(content: &str) -> Self {
        ContextItem::System {
            content: format!("[System Notification]\n{}", content),
        }
    }

    /// Convert a batch of ToolResult items into synthetic User messages
    /// for round-trip injection. This is used when:
    ///   1. The provider doesn't support native tool result messages
    ///   2. After compaction, tool results need to be re-injected as context
    ///   3. During crash recovery, tool results need to be replayed
    ///
    /// Each ToolResult is converted to a User message with the tool name
    /// and call_id embedded for traceability. Non-ToolResult items are
    /// filtered out.
    pub fn batch_tool_results_as_users(
        items: &[ContextItem],
        tool_names: &std::collections::HashMap<ToolCallId, String>,
    ) -> Vec<Self> {
        items
            .iter()
            .filter_map(|item| match item {
                ContextItem::ToolResult {
                    call_id,
                    content,
                    is_error,
                } => {
                    let tool_name = tool_names
                        .get(call_id)
                        .map(|s| s.as_str())
                        .unwrap_or("unknown");
                    let prefix = if *is_error { "[Tool Error" } else { "[Tool Result" };
                    Some(ContextItem::User {
                        content: format!(
                            "{}: {} (call_id: {})]\n{}",
                            prefix, tool_name, call_id, content
                        ),
                        message_id: Some(format!("tool_resp_{}", call_id)),
                    })
                }
                _ => None,
            })
            .collect()
    }

    /// Build a compaction notification message that summarizes what was
    /// compacted and provides the model with context about the compaction.
    /// Used after compaction to inform the model that older context has
    /// been summarized.
    pub fn compaction_notification(
        summary: &str,
        items_compacted: usize,
        tokens_freed: usize,
    ) -> Self {
        ContextItem::System {
            content: format!(
                "[Compaction Notification]\n\
                 Compacted {} items, freed ~{} tokens.\n\
                 Summary:\n{}",
                items_compacted, tokens_freed, summary
            ),
        }
    }
}

// ── Evidence provenance (doc 11 §16) ──────────────────────────────

/// Reference to a rollout evidence range, attached to compaction summaries
/// so compressed content always has a traceable provenance chain.
/// (doc 11 §16)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceRef {
    /// Start of the rollout seq range this evidence covers.
    pub rollout_seq_start: u64,
    /// End (inclusive) of the rollout seq range.
    pub rollout_seq_end: u64,
    /// Optional hash of the artifact backing this evidence.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_hash: Option<String>,
    /// What kind of source this evidence came from.
    pub source_kind: EvidenceSourceKind,
}

/// The kind of source an EvidenceRef points to.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceSourceKind {
    /// User message in the rollout.
    UserMessage,
    /// Model/assistant output.
    AssistantOutput,
    /// Tool call and its result.
    ToolCall,
    /// System reminder or runtime notification.
    System,
    /// A previous compaction summary.
    CompactionSummary,
}

// ── Structured compaction summary (doc 11 §16) ───────────────────

/// Structured compaction summary (doc 11 §16). The model returns this
/// structured result rather than free-form Markdown. Each key item can
/// carry EvidenceRef for provenance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionSummaryV2 {
    pub schema_version: u32,
    /// The session's primary objective.
    pub objective: String,
    /// User-imposed constraints discovered so far.
    #[serde(default)]
    pub user_constraints: Vec<String>,
    /// Key decisions made.
    #[serde(default)]
    pub decisions: Vec<CompactionEntry>,
    /// Work that has been completed.
    #[serde(default)]
    pub completed_work: Vec<CompactionEntry>,
    /// Attempts that failed.
    #[serde(default)]
    pub failed_attempts: Vec<CompactionEntry>,
    /// Validations performed.
    #[serde(default)]
    pub validations: Vec<CompactionEntry>,
    /// Unresolved questions.
    #[serde(default)]
    pub unresolved_questions: Vec<String>,
    /// Suggested next action.
    #[serde(default)]
    pub next_action: Option<String>,
    /// Evidence references for all claims in this summary.
    #[serde(default)]
    pub evidence_refs: Vec<EvidenceRef>,
    /// Free-form narrative connecting the structured fields.
    #[serde(default)]
    pub narrative: String,
}

/// A single entry in a structured compaction summary, optionally backed
/// by evidence references.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionEntry {
    pub text: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence_refs: Vec<EvidenceRef>,
}

impl CompactionSummaryV2 {
    /// Current schema version produced by this implementation.
    pub const SCHEMA_VERSION: u32 = 1;

    /// Create a new structured summary with the given objective.
    pub fn new(objective: impl Into<String>) -> Self {
        Self {
            schema_version: Self::SCHEMA_VERSION,
            objective: objective.into(),
            user_constraints: Vec::new(),
            decisions: Vec::new(),
            completed_work: Vec::new(),
            failed_attempts: Vec::new(),
            validations: Vec::new(),
            unresolved_questions: Vec::new(),
            next_action: None,
            evidence_refs: Vec::new(),
            narrative: String::new(),
        }
    }

    /// Record a key decision, optionally backed by evidence.
    pub fn add_decision(
        &mut self,
        text: impl Into<String>,
        evidence_refs: Vec<EvidenceRef>,
    ) {
        self.decisions.push(CompactionEntry {
            text: text.into(),
            evidence_refs,
        });
    }

    /// Record a unit of completed work, optionally backed by evidence.
    pub fn add_completed_work(
        &mut self,
        text: impl Into<String>,
        evidence_refs: Vec<EvidenceRef>,
    ) {
        self.completed_work.push(CompactionEntry {
            text: text.into(),
            evidence_refs,
        });
    }

    /// Record a failed attempt, optionally backed by evidence.
    pub fn add_failed_attempt(
        &mut self,
        text: impl Into<String>,
        evidence_refs: Vec<EvidenceRef>,
    ) {
        self.failed_attempts.push(CompactionEntry {
            text: text.into(),
            evidence_refs,
        });
    }

    /// Render the structured summary as a flat text blob, suitable for
    /// dropping into the legacy `ContextItem::CompactionSummary { summary }`
    /// field so existing consumers keep working.
    pub fn to_flat_summary(&self) -> String {
        let mut out = String::new();
        out.push_str("# Compaction Summary\n\n");
        out.push_str(&format!("Objective: {}\n", self.objective));

        render_entry_list(&mut out, "User Constraints", &self.user_constraints.iter().map(String::as_str).collect::<Vec<_>>());
        render_compaction_entries(&mut out, "Decisions", &self.decisions);
        render_compaction_entries(&mut out, "Completed Work", &self.completed_work);
        render_compaction_entries(&mut out, "Failed Attempts", &self.failed_attempts);
        render_compaction_entries(&mut out, "Validations", &self.validations);
        render_entry_list(&mut out, "Unresolved Questions", &self.unresolved_questions.iter().map(String::as_str).collect::<Vec<_>>());

        if let Some(next) = &self.next_action {
            out.push_str(&format!("\nNext Action: {}\n", next));
        }
        if !self.narrative.is_empty() {
            out.push_str(&format!("\nNarrative:\n{}\n", self.narrative));
        }
        out
    }

    /// Total number of evidence references attached anywhere in this
    /// summary (top-level + per-entry).
    pub fn total_evidence_count(&self) -> usize {
        let mut count = self.evidence_refs.len();
        for entries in [
            &self.decisions,
            &self.completed_work,
            &self.failed_attempts,
            &self.validations,
        ] {
            count += entries.iter().map(|e| e.evidence_refs.len()).sum::<usize>();
        }
        count
    }
}

fn render_compaction_entries(out: &mut String, title: &str, entries: &[CompactionEntry]) {
    if entries.is_empty() {
        return;
    }
    out.push_str(&format!("\n## {}\n", title));
    for entry in entries {
        out.push_str(&format!("- {}", entry.text));
        if !entry.evidence_refs.is_empty() {
            let ranges: Vec<String> = entry
                .evidence_refs
                .iter()
                .map(|e| format!("seq[{}..{}]", e.rollout_seq_start, e.rollout_seq_end))
                .collect();
            out.push_str(&format!(" [evidence: {}]", ranges.join(", ")));
        }
        out.push('\n');
    }
}

fn render_entry_list(out: &mut String, title: &str, items: &[&str]) {
    if items.is_empty() {
        return;
    }
    out.push_str(&format!("\n## {}\n", title));
    for item in items {
        out.push_str(&format!("- {}\n", item));
    }
}

#[cfg(test)]
mod evidence_tests {
    use super::*;

    #[test]
    fn evidence_ref_serializes_snake_case() {
        let ev = EvidenceRef {
            rollout_seq_start: 1,
            rollout_seq_end: 5,
            artifact_hash: Some("abc".into()),
            source_kind: EvidenceSourceKind::ToolCall,
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert!(json.contains("\"source_kind\":\"tool_call\""));
        let back: EvidenceRef = serde_json::from_str(&json).unwrap();
        assert_eq!(back.source_kind, EvidenceSourceKind::ToolCall);
        assert_eq!(back.rollout_seq_end, 5);
    }

    #[test]
    fn summary_v2_new_sets_objective_and_schema() {
        let s = CompactionSummaryV2::new("Ship feature X");
        assert_eq!(s.objective, "Ship feature X");
        assert_eq!(s.schema_version, CompactionSummaryV2::SCHEMA_VERSION);
        assert!(s.decisions.is_empty());
        assert_eq!(s.total_evidence_count(), 0);
    }

    #[test]
    fn add_methods_accumulate_entries_with_evidence() {
        let mut s = CompactionSummaryV2::new("obj");
        s.add_decision("decide A", vec![EvidenceRef {
            rollout_seq_start: 0,
            rollout_seq_end: 2,
            artifact_hash: None,
            source_kind: EvidenceSourceKind::UserMessage,
        }]);
        s.add_completed_work("did B", vec![]);
        s.add_failed_attempt("tried C", vec![
            EvidenceRef { rollout_seq_start: 3, rollout_seq_end: 4, artifact_hash: None, source_kind: EvidenceSourceKind::AssistantOutput },
            EvidenceRef { rollout_seq_start: 7, rollout_seq_end: 9, artifact_hash: None, source_kind: EvidenceSourceKind::ToolCall },
        ]);
        assert_eq!(s.decisions.len(), 1);
        assert_eq!(s.completed_work.len(), 1);
        assert_eq!(s.failed_attempts.len(), 1);
        assert_eq!(s.total_evidence_count(), 3);
    }

    #[test]
    fn flat_summary_renders_structured_fields() {
        let mut s = CompactionSummaryV2::new("Ship feature X");
        s.user_constraints.push("must work offline".into());
        s.add_decision("use sqlite", vec![]);
        s.unresolved_questions.push("how to sync?".into());
        s.next_action = Some("write migration".into());
        s.narrative = "We explored options.".into();

        let flat = s.to_flat_summary();
        assert!(flat.contains("Objective: Ship feature X"));
        assert!(flat.contains("## User Constraints"));
        assert!(flat.contains("must work offline"));
        assert!(flat.contains("## Decisions"));
        assert!(flat.contains("use sqlite"));
        assert!(flat.contains("## Unresolved Questions"));
        assert!(flat.contains("how to sync?"));
        assert!(flat.contains("Next Action: write migration"));
        assert!(flat.contains("We explored options."));
    }

    #[test]
    fn flat_summary_round_trips_into_legacy_field() {
        let mut s = CompactionSummaryV2::new("obj");
        s.add_completed_work("task done", vec![]);
        let flat = s.to_flat_summary();
        let item = ContextItem::CompactionSummary {
            summary: flat.clone(),
            window_number: 1,
        };
        match item {
            ContextItem::CompactionSummary { summary, .. } => assert_eq!(summary, flat),
            _ => panic!("wrong variant"),
        }
    }
}
